# Generated by Django 3.1.5 on 2021-02-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='user',
            new_name='userId',
        ),
    ]
